# 启动后直接访问：http://localhost:8080 跳转到登录页面
# 初始登录用户名/密码：admin/test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.128:3306/flowable
    username: root
    password: root