spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/flowable
    #username: root
    #password: root
    driver-class-name: org.h2.Driver
    # flowable 不能加 ;MODE=MYSQL，否则报错
    url: jdbc:h2:file:./h2/vitality;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
decorator:
  datasource:
    enabled: true
