spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.128:3306/flowable
    username: root
    password: root
decorator:
  datasource:
    enabled: true
